// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayefucundknjoumtqdlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZWZ1Y3VuZGtuam91bXRxZGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MzkxNjIsImV4cCI6MjA3NDUxNTE2Mn0.S3T3S6qfOLSfbvb4NhElIRpqYYrZyE-6vdIVMkrzcOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});